/** Auto-generated by scripts/sync-aesthetics.ts — do not edit. */
import apple from './apple.json'
import notion from './notion.json'
import dell_1996 from './dell-1996.json'
import stripe from './stripe.json'
import linear from './linear.json'
import vercel from './vercel.json'
import spotify from './spotify.json'
import supabase from './supabase.json'
import claude from './claude.json'
import figma from './figma.json'
import sentry from './sentry.json'
import runway from './runway.json'
import shopify from './shopify.json'
import cursor from './cursor.json'
import raycast from './raycast.json'
import framer from './framer.json'
import voltagent from './voltagent.json'
import wise from './wise.json'
import tesla from './tesla.json'
import biennale_yellow from './biennale-yellow.json'
import blockframe from './blockframe.json'
import blue_professional from './blue-professional.json'
import bold_poster from './bold-poster.json'
import broadside from './broadside.json'
import capsule from './capsule.json'
import cartesian from './cartesian.json'
import cobalt_grid from './cobalt-grid.json'
import coral from './coral.json'
import creative_mode from './creative-mode.json'
import daisy_days from './daisy-days.json'
import editorial_forest from './editorial-forest.json'
import style_swiss_pulse from './style-swiss-pulse.json'
import style_velvet_standard from './style-velvet-standard.json'
import style_deconstructed from './style-deconstructed.json'
import style_maximalist_type from './style-maximalist-type.json'
import style_data_drift from './style-data-drift.json'
import style_soft_signal from './style-soft-signal.json'
import style_folk_frequency from './style-folk-frequency.json'
import style_shadow_cut from './style-shadow-cut.json'

export const parsedDesignSources = {
  'apple': apple,
  'notion': notion,
  'dell-1996': dell_1996,
  'stripe': stripe,
  'linear': linear,
  'vercel': vercel,
  'spotify': spotify,
  'supabase': supabase,
  'claude': claude,
  'figma': figma,
  'sentry': sentry,
  'runway': runway,
  'shopify': shopify,
  'cursor': cursor,
  'raycast': raycast,
  'framer': framer,
  'voltagent': voltagent,
  'wise': wise,
  'tesla': tesla,
  'biennale-yellow': biennale_yellow,
  'blockframe': blockframe,
  'blue-professional': blue_professional,
  'bold-poster': bold_poster,
  'broadside': broadside,
  'capsule': capsule,
  'cartesian': cartesian,
  'cobalt-grid': cobalt_grid,
  'coral': coral,
  'creative-mode': creative_mode,
  'daisy-days': daisy_days,
  'editorial-forest': editorial_forest,
  'style-swiss-pulse': style_swiss_pulse,
  'style-velvet-standard': style_velvet_standard,
  'style-deconstructed': style_deconstructed,
  'style-maximalist-type': style_maximalist_type,
  'style-data-drift': style_data_drift,
  'style-soft-signal': style_soft_signal,
  'style-folk-frequency': style_folk_frequency,
  'style-shadow-cut': style_shadow_cut,
} as const

export type ParsedDesignId = keyof typeof parsedDesignSources
